import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { LockKeyhole, Mail, Vote, ShieldCheck, BarChart3, Users } from "lucide-react";
import toast from "react-hot-toast";
import API from "../services/api";
import useAuth from "../context/useAuth";

export default function Login(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[loading,setLoading]=useState(false);const{loginUser}=useAuth();const navigate=useNavigate();async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);try{const res=await API.post("/auth/login",{email,password});loginUser(res.data.user,res.data.token);toast.success("Signed in successfully");navigate("/dashboard")}catch(error:unknown){toast.error(axios.isAxiosError(error)?error.response?.data?.message||"Invalid login details":"Invalid login details")}finally{setLoading(false)}}return <div className="grid min-h-screen bg-white lg:grid-cols-[1.05fr_.95fr]">
<section className="flex min-h-screen flex-col px-5 py-6 sm:px-10 lg:px-16 xl:px-24"><Link to="/" className="flex w-fit items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-white"><Vote size={20}/></div><div><p className="font-bold tracking-tight">AwardVote</p><p className="text-[10px] text-slate-400">Secure digital elections</p></div></Link><div className="my-auto w-full max-w-md py-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Administrator access</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Welcome back.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Sign in to manage candidates, monitor voting and control your election.</p><form onSubmit={submit} className="mt-8 space-y-5"><div><label className="mb-2 block text-sm font-semibold">Email address</label><div className="relative"><Mail size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@organization.com" className="h-12 w-full rounded-xl border bg-white pl-11 pr-4 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-violet-100"/></div></div><div><div className="mb-2 flex justify-between"><label className="text-sm font-semibold">Password</label><Link to="/forgot-password" className="text-xs font-semibold text-primary">Forgot password?</Link></div><div className="relative"><LockKeyhole size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" className="h-12 w-full rounded-xl border bg-white pl-11 pr-4 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-violet-100"/></div></div><button disabled={loading} className="h-12 w-full rounded-xl bg-primary text-sm font-bold text-white shadow-lg shadow-violet-200 transition hover:brightness-110 disabled:opacity-60">{loading?"Signing in...":"Sign in to dashboard"}</button></form><p className="mt-6 text-sm text-slate-500">New to AwardVote? <Link to="/signup" className="font-bold text-primary">Create an account</Link></p></div><p className="text-xs text-slate-400">© {new Date().getFullYear()} AwardVote. Secure voting infrastructure.</p></section>
<section className="relative hidden overflow-hidden bg-[#11152b] p-10 text-white lg:flex lg:flex-col lg:justify-between xl:p-14"><div className="absolute inset-0 voting-grid opacity-20"/><div className="absolute -right-24 top-10 h-80 w-80 rounded-full bg-violet-500/25 blur-3xl"/><div className="relative"><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-violet-200">Election command center</span></div><div className="relative max-w-xl"><h2 className="text-4xl font-bold leading-tight tracking-tight xl:text-5xl">Run elections people can trust.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-300">Everything you need to manage candidates, control voting windows and monitor participation from one secure workspace.</p><div className="mt-9 grid grid-cols-3 gap-3">{[[ShieldCheck,"Secure","Protected voting"],[BarChart3,"Live","Vote analytics"],[Users,"Simple","Candidate tools"]].map(([I,a,b]:any)=><div key={a} className="rounded-2xl border border-white/10 bg-white/5 p-4"><I size={20} className="text-violet-300"/><p className="mt-3 text-sm font-bold">{a}</p><p className="mt-1 text-[11px] text-slate-400">{b}</p></div>)}</div></div><p className="relative text-xs text-slate-500">Built for awards, associations and organizations.</p></section></div>}
