import{Response}from"express";import{supabase}from"../lib/supabase";import type{AuthRequest}from"../middleware/authMiddleware";import{writeAudit}from"../utils/auditLog";import{randomBytes}from"crypto";
const hex=(v:any,f:string)=>/^#[0-9a-f]{6}$/i.test(String(v||""))?String(v):f;
export async function getBranding(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const r=await supabase.from("award_spaces").select("id,name,slug,description,logo_url,banner_url,primary_color,accent_color,organizer_name,website_url,custom_domain,domain_status,domain_verification_token,domain_verified_at").eq("id",req.user.awardSpace).single();if(r.error)throw r.error;return res.json(r.data)}catch(e){return res.status(500).json({message:"Failed to load branding"})}}
export async function updateBranding(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const payload={logo_url:String(req.body.logoUrl||"").trim()||null,banner_url:String(req.body.bannerUrl||"").trim()||null,primary_color:hex(req.body.primaryColor,"#0b1220"),accent_color:hex(req.body.accentColor,"#f4b41a"),organizer_name:String(req.body.organizerName||"").trim()||null,website_url:String(req.body.websiteUrl||"").trim()||null};const r=await supabase.from("award_spaces").update(payload).eq("id",req.user.awardSpace).select("*").single();if(r.error)throw r.error;await writeAudit({awardSpace:req.user.awardSpace,adminId:req.user.id,req,action:"branding.updated",entityType:"event",entityId:req.user.awardSpace,details:payload});return res.json(r.data)}catch(e){console.error(e);return res.status(500).json({message:"Failed to update branding"})}}

const cleanDomain=(v:any)=>String(v||"").trim().toLowerCase().replace(/^https?:\/\//,"").replace(/\/$/,"");
export async function configureDomain(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const domain=cleanDomain(req.body.domain);if(!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i.test(domain))return res.status(400).json({message:"Enter a valid domain such as vote.example.com"});const token="awardvote-verification="+randomBytes(18).toString("hex");const r=await supabase.from("award_spaces").update({custom_domain:domain,domain_status:"pending_dns",domain_verification_token:token,domain_verified_at:null}).eq("id",req.user.awardSpace).select("custom_domain,domain_status,domain_verification_token").single();if(r.error){if((r.error as any).code==="23505")return res.status(409).json({message:"This domain is already connected to another event"});throw r.error}await writeAudit({awardSpace:req.user.awardSpace,adminId:req.user.id,req,action:"domain.configured",entityType:"event",entityId:req.user.awardSpace,details:{domain}});return res.json({...r.data,dns:{type:"TXT",host:"_awardvote."+domain,value:token}})}catch(e){console.error(e);return res.status(500).json({message:"Failed to configure custom domain"})}}
export async function verifyDomain(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const e=await supabase.from("award_spaces").select("custom_domain,domain_verification_token").eq("id",req.user.awardSpace).single();if(e.error)throw e.error;if(!e.data.custom_domain)return res.status(400).json({message:"Configure a domain first"});const dns=await import("dns/promises");let values:string[]=[];try{values=(await dns.resolveTxt("_awardvote."+e.data.custom_domain)).flat()}catch{}if(!values.includes(e.data.domain_verification_token))return res.status(400).json({message:"DNS verification record not found yet"});const now=new Date().toISOString();const r=await supabase.from("award_spaces").update({domain_status:"verified",domain_verified_at:now}).eq("id",req.user.awardSpace).select("custom_domain,domain_status,domain_verified_at").single();if(r.error)throw r.error;await writeAudit({awardSpace:req.user.awardSpace,adminId:req.user.id,req,action:"domain.verified",entityType:"event",entityId:req.user.awardSpace,details:{domain:e.data.custom_domain}});return res.json(r.data)}catch(e){console.error(e);return res.status(500).json({message:"Domain verification failed"})}}
export async function resolveDomain(req:any,res:Response){try{const domain=cleanDomain(req.params.domain);const r=await supabase.from("award_spaces").select("id,name,slug,custom_domain,domain_status").eq("custom_domain",domain).eq("domain_status","verified").maybeSingle();if(r.error)throw r.error;if(!r.data)return res.status(404).json({message:"Domain not connected"});return res.json({event:r.data})}catch{return res.status(500).json({message:"Could not resolve domain"})}}
