import { Response } from "express";
import { supabase } from "../lib/supabase";
import type { AuthRequest } from "../middleware/authMiddleware";
import { generateSlug } from "../utils/generateSlug";
import { generateToken } from "../utils/generateToken";
import { writeAudit } from "../utils/auditLog";

async function membership(adminId:string,spaceId:string){const r=await supabase.from("admin_award_spaces").select("role").eq("admin_id",adminId).eq("award_space_id",spaceId).maybeSingle();if(r.error)throw r.error;return r.data}
export async function listEvents(req:AuthRequest,res:Response){try{if(!req.user)return res.status(401).json({message:"Unauthorized"});const m=await supabase.from("admin_award_spaces").select("award_space_id,role").eq("admin_id",req.user.id);if(m.error)throw m.error;const ids=(m.data||[]).map(x=>x.award_space_id);if(!ids.length)return res.json({events:[],activeEventId:req.user.awardSpace});const e=await supabase.from("award_spaces").select("*").in("id",ids).order("created_at",{ascending:false});if(e.error)throw e.error;const roles=new Map((m.data||[]).map(x=>[x.award_space_id,x.role]));return res.json({activeEventId:req.user.awardSpace,events:(e.data||[]).map(x=>({...x,role:roles.get(x.id)}))})}catch(e){console.error(e);return res.status(500).json({message:"Failed to load events"})}}
export async function createEvent(req:AuthRequest,res:Response){try{if(!req.user)return res.status(401).json({message:"Unauthorized"});const name=String(req.body.name||"").trim(),description=String(req.body.description||"").trim(),eventType=req.body.eventType==="election"?"election":"award",electionKind=eventType==="election"?String(req.body.electionKind||"organization"):null;if(name.length<3)return res.status(400).json({message:"Event name is required"});let slug=generateSlug(name);const exists=await supabase.from("award_spaces").select("id").eq("slug",slug).maybeSingle();if(exists.data)slug=generateSlug(name+"-"+Date.now());const created=await supabase.from("award_spaces").insert({name,slug,description,is_active:true,event_type:eventType,election_kind:electionKind}).select("*").single();if(created.error)throw created.error;const member=await supabase.from("admin_award_spaces").insert({admin_id:req.user.id,award_space_id:created.data.id,role:"owner"});if(member.error)throw member.error;const settings=await supabase.from("settings").insert({award_space_id:created.data.id,voting_start:null,voting_end:null,candidate_can_view_votes:true,vote_price_minor:100,currency:"GHS"});if(settings.error)throw settings.error;await writeAudit({awardSpace:created.data.id,adminId:req.user.id,req,action:"event.created",entityType:"event",entityId:created.data.id,details:{name:created.data.name,slug:created.data.slug,eventType}});return res.status(201).json({event:created.data})}catch(e){console.error(e);return res.status(500).json({message:"Failed to create event"})}}
export async function switchEvent(req:AuthRequest,res:Response){try{if(!req.user)return res.status(401).json({message:"Unauthorized"});const eventId=String(req.params.id||"");const member=await membership(req.user.id,eventId);if(!member)return res.status(403).json({message:"You do not have access to this event"});const event=await supabase.from("award_spaces").select("id,name,event_type").eq("id",eventId).single();if(event.error)throw event.error;const token=generateToken({id:req.user.id,email:req.user.email,name:req.user.name,awardSpace:eventId});return res.json({token,user:{id:req.user.id,email:req.user.email,name:req.user.name,awardSpace:eventId,awardName:event.data.name,eventType:event.data.event_type,eventRole:member.role},role:member.role})}catch(e){console.error(e);return res.status(500).json({message:"Failed to switch event"})}}

const stages=["setup","nominations","voting","results","completed","archived"] as const;
export async function updateLifecycle(req:AuthRequest,res:Response){try{if(!req.user?.id||!req.user.awardSpace)return res.status(401).json({message:"Unauthorized"});const stage=String(req.body.stage||"") as typeof stages[number];if(!stages.includes(stage))return res.status(400).json({message:"Invalid lifecycle stage"});const member=await membership(req.user.id,req.user.awardSpace);if(!member||!["owner","admin"].includes(member.role))return res.status(403).json({message:"Only owners and admins can change event lifecycle"});const current=await supabase.from("award_spaces").select("id,name,event_type,lifecycle_stage").eq("id",req.user.awardSpace).single();if(current.error)throw current.error;if(current.data.event_type==="election"){if(current.data.lifecycle_stage==="archived")return res.status(409).json({message:"An archived election is permanently read-only"});return res.status(409).json({message:"Use Election Controls, Results Certification and Election Archive to manage an election lifecycle"})}const now=new Date().toISOString(),u=await supabase.from("award_spaces").update({lifecycle_stage:stage,lifecycle_updated_at:now,is_active:stage!=="archived"}).eq("id",req.user.awardSpace).select("*").single();if(u.error)throw u.error;if(stage==="nominations")await supabase.from("settings").update({nominations_open:true}).eq("award_space_id",req.user.awardSpace);if(["voting","results","completed","archived"].includes(stage))await supabase.from("settings").update({nominations_open:false}).eq("award_space_id",req.user.awardSpace);await writeAudit({awardSpace:req.user.awardSpace,adminId:req.user.id,req,action:"event.lifecycle_changed",entityType:"event",entityId:req.user.awardSpace,details:{from:current.data.lifecycle_stage||"setup",to:stage}});return res.json({event:u.data})}catch(e){console.error(e);return res.status(500).json({message:"Failed to update event lifecycle"})}}
