import { Response } from "express";
import { supabase } from "../lib/supabase";
import type { AuthRequest } from "../middleware/authMiddleware";
import { getEventRole, type EventRole } from "../middleware/eventAccess";
import { writeAudit } from "../utils/auditLog";
const allowed: EventRole[] = ["owner","admin","finance","viewer"];
export async function getTeam(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const role=await getEventRole(req.user.id,req.user.awardSpace);const r=await supabase.from("admin_award_spaces").select("admin_id,role,created_at,admins(id,name,email)").eq("award_space_id",req.user.awardSpace).order("created_at",{ascending:true});if(r.error)throw r.error;return res.json({role,members:r.data||[],capabilities:role?({owner:["event.manage","nominees.manage","settings.manage","payments.read","payments.reconcile","integrity.review","votes.adjust","team.manage","audit.read"],admin:["nominees.manage","settings.manage","payments.read","integrity.review","audit.read"],finance:["payments.read","payments.reconcile","integrity.review","audit.read"],viewer:["payments.read","audit.read"]} as any)[role]:[]})}catch(e){console.error(e);return res.status(500).json({message:"Failed to load team"})}}
export async function addMember(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const email=String(req.body.email||"").trim().toLowerCase(),role=String(req.body.role||"") as EventRole;if(!email||!allowed.includes(role)||role==="owner")return res.status(400).json({message:"Valid email and role are required"});const a=await supabase.from("admins").select("id,name,email").eq("email",email).maybeSingle();if(a.error)throw a.error;if(!a.data)return res.status(404).json({message:"That person needs an AwardVote account before being added"});const up=await supabase.from("admin_award_spaces").upsert({admin_id:a.data.id,award_space_id:req.user.awardSpace,role},{onConflict:"admin_id,award_space_id"});if(up.error)throw up.error;await writeAudit({awardSpace:req.user.awardSpace,adminId:req.user.id,action:"team.member_added",entityType:"admin",entityId:a.data.id,details:{email,role}});return res.status(201).json({message:"Team member added"})}catch(e){console.error(e);return res.status(500).json({message:"Failed to add team member"})}}
export async function updateMember(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const id=String(req.params.id||""),role=String(req.body.role||"") as EventRole;if(!id||!allowed.includes(role)||role==="owner")return res.status(400).json({message:"Valid member and role are required"});const current=await supabase.from("admin_award_spaces").select("role").eq("admin_id",id).eq("award_space_id",req.user.awardSpace).maybeSingle();if(!current.data)return res.status(404).json({message:"Member not found"});if(current.data.role==="owner")return res.status(403).json({message:"The event owner cannot be changed here"});const u=await supabase.from("admin_award_spaces").update({role}).eq("admin_id",id).eq("award_space_id",req.user.awardSpace);if(u.error)throw u.error;await writeAudit({awardSpace:req.user.awardSpace,adminId:req.user.id,action:"team.role_changed",entityType:"admin",entityId:id,details:{from:current.data.role,to:role}});return res.json({message:"Role updated"})}catch(e){console.error(e);return res.status(500).json({message:"Failed to update role"})}}
export async function removeMember(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const id=String(req.params.id||"");const current=await supabase.from("admin_award_spaces").select("role").eq("admin_id",id).eq("award_space_id",req.user.awardSpace).maybeSingle();if(!current.data)return res.status(404).json({message:"Member not found"});if(current.data.role==="owner")return res.status(403).json({message:"The event owner cannot be removed"});const d=await supabase.from("admin_award_spaces").delete().eq("admin_id",id).eq("award_space_id",req.user.awardSpace);if(d.error)throw d.error;await writeAudit({awardSpace:req.user.awardSpace,adminId:req.user.id,action:"team.member_removed",entityType:"admin",entityId:id,details:{role:current.data.role}});return res.json({message:"Team member removed"})}catch(e){console.error(e);return res.status(500).json({message:"Failed to remove team member"})}}
export async function getAuditLogs(req:AuthRequest,res:Response){try{if(!req.user?.awardSpace)return res.status(401).json({message:"Unauthorized"});const r=await supabase.from("audit_logs").select("id,action,entity_type,entity_id,actor_role,ip_hash,user_agent,request_id,details,created_at,admins(name,email)").eq("award_space_id",req.user.awardSpace).order("created_at",{ascending:false}).limit(500);if(r.error)throw r.error;return res.json({logs:r.data||[]})}catch(e){console.error(e);return res.status(500).json({message:"Failed to load audit logs"})}}
